### ISSUE TITLE
;로 분리하여 입력받기

### ISSUE THREAD

**Issue by niamu01** [Matching42/Matching42_minishell#14]

**Comment by niamu01** [comment]
https://humonnom.tistory.com/entry/minishell-Shell%EC%9D%B4%EB%9E%80-%EA%B7%B8%EB%A6%AC%EA%B3%A0-Shell%EC%9D%B4-%ED%95%98%EB%8A%94-%EC%9D%BC
⬆️ ⬆️ ⬆️ ⬆️ ⬆️ 
;을 기준으로 token으로 나누고 token을 다시 command와 argument로 나눈다! 라는 내용과
미니쉘의 이것저것이 적혀있는 글입니다

**Comment by notusing11** [comment]
리다이렉트로 문장별 단어별 해석을 하다보니 자연스레 해결했습니다! 

리드라인으로 받은 문자열을 세미콜론으로 먼저 나누는 단계를 추가했습니다!
