### ISSUE TITLE
내장함수_exit

### ISSUE THREAD

**Issue by niamu01** [Matching42/Matching42_minishell#18]

**Comment by notusing11** [comment]
동적할당한 메모리주소나 생성한 파일디스크립터를 모두 저장하는 구조체가 필요할 것으로 보입니다!!

프로그램 시작할때 구조체를 memset해둔 다음 
null이 아닌 모든 메모리 주소 혹은 fd값을 해제해주는 과정 = exit

**Comment by notusing11** [comment]
◦ exit with no options

종료코드가 0~255 범위에 벗어나거나 숫자가 아닌 경우까지 고려하지는 않음

**Comment by notusing11** [comment]
헐 no argument가 아니네요ㅠㅠㅠ 
exit의 인자 해석 및 종료코드 범위로 인한 오류메세지 작업 시작합니다ㅠㅠ
