### ISSUE TITLE
프롬프트 띄우기

### ISSUE THREAD

**Issue by notusing11** [Matching42/Matching42_minishell#3]
서브젝트
> Show a prompt when waiting for a new command.
새로운 명령어를 입력할 수 있는 프롬프트를 보여줘야 합니다.

**Comment by notusing11** [comment]
readline 함수로 해결가능
반환값은 동적할당된 문자열

**Comment by niamu01** [comment]
https://brennan.io/2015/01/16/write-a-shell-in-c/
