### ISSUE TITLE
PATH에서 실행파일을 찾아 실행하기

### ISSUE THREAD

**Issue by notusing11** [Matching42/Matching42_minishell#5]
서브젝트 
> Search and launch the right executable (based on the PATH variable or by using relative or absolute path)
(PATH 변수나 상대, 절대 경로를 활용하여) 올바른 실행 파일을 찾아 실행할 수 있어야 합니다.

**Comment by notusing11** [comment]
환경변수path에 콜론 :으로 구분된 경로를 모두 순회하며 
입력된 실행파일의 이름과 일치하는 파일이 있는지 확인하고 실행해야

환경변수 세팅이 필요

**Comment by niamu01** [comment]
1. strjoin을 이용해 '/'과 사용하려는 파일(cat, ls 등)을 붙여줌
2. $PATH를 ':'로 ft_split하여 여러 경로를 나눠둠
3. 1번과 2번을 strjoin함
4. 3번에서 나온 경로들 중 유효한 경로를 stat함수를 통해 찾음
