### ISSUE TITLE
이번주

### ISSUE THREAD

**Issue by niamu01** [Matching42/Matching42_minishell#65]

**Comment by niamu01** [comment]
- [ ] unset, export에 abc#a 들어갔을때 오류처리 해주기

**Comment by niamu01** [comment]
- [ ] -Wall -Werror -Wextra 붙여서 에러 확인

**Comment by notusing11** [comment]
![image](https://user-images.githubusercontent.com/74622889/149962872-a73e665f-710c-424b-86e8-5fe6eae2f28a.png)

이게 오류나네요ㅠㅠ 확인해주세요

**Comment by niamu01** [comment]
export는 = 전까지만 확인하는걸 안추가했었네요,_, 메인으로 푸시했습니다
